# Generated by Django 5.0.2 on 2024-03-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_news_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AddField(
            model_name='news',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
