# Generated by Django 5.0.2 on 2024-03-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
