# Generated by Django 5.0.2 on 2024-03-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_news_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_date',
            field=models.DateTimeField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fdefault&psig=AOvVaw2Cux9WSXZRad0Bo9SPG5Pq&ust=1709720822210000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCKD2vcT03IQDFQAAAAAdAAAAABAE'),
        ),
    ]
