# Generated by Django 5.0.2 on 2024-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOz18-q0kyakVcxdTuLlyyHVN5npGJi92ou04GZgFVLNWhTim5JlQBwA1hPJMzM90_Uas&usqp=CAU'),
        ),
    ]
